### ISSUE TITLE
Hover options

### ISSUE THREAD

**Issue by PrateekGoyal18** [yasersakkaf/Visualize-Women-Harrasment-in-India-using-GeoPandas#1]
Is there a possibility to add hover properties to the graph rendered?
I am trying to pass this graph to HTML through flask and want the user to see the values when they hover over each state.

**Comment by yasersakkaf** [comment]
You'll have to use something like Bokeh to get such properties.
This is a good example to refer to:
https://towardsdatascience.com/a-complete-guide-to-an-interactive-geographical-map-using-python-f4c5197e23e0
