### ISSUE TITLE
Issue with District Map

### ISSUE THREAD

**Issue by Gautamshahi** [yasersakkaf/Visualize-Women-Harrasment-in-India-using-GeoPandas#2]
Hello,

In the district map, the map is not an official map, some part of Kashmir is missing? How can we get the data for full map, even we don't any data in Kashmir(under the control fo Pakistan)?

I wanted to put the district map, but it's not good to show the wrong map

**Comment by Gautamshahi** [comment]
Hi,

Is there any update on this?

**Comment by yasersakkaf** [comment]
Hi @Gautamshahi , I used maps that were available for demo purpose. I too am searching for more updated and correct ones. Will notify you if I find something.
